apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
stringData:
  objstore.yml: |
    type: S3
    config:
      endpoint: minio-api.local
      bucket: default
      access_key: UdYrReVdlTrkUJZQn83r
      secret_key: r7S29z5390da3g2OULBt6bd2Vr5OeT3E0tMDdedN
      insecure: true