kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: "web-app-example"
          static_configs:
            - targets:
                - "web-app-example.web.svc.cluster.local:3000"
    adminUser: admin
    adminPassword: admin
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.local
      paths:
        - /
  nodeExporter:
    enabled: true
  grafana:
    adminUser: admin
    adminPassword: admin
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.local
      paths: /