apiVersion: batch/v1
kind: CronJob
metadata:
  name: push-metrics
  namespace: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: push-metrics
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "cronjob_metric{job=\"cronjob\",status=\"success\"} 1" | curl --data-binary @- http://pushgateway.cronjob.svc.cluster.local:9091/metrics/job/cronjob
          restartPolicy: OnFailure