apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: cronjob
  labels:
    app: pushgateway
spec:
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: pushgateway
  type: ClusterIP