apiVersion: v2
name: minio
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: minio
    version: 16.0.0
    repository: oci://registry-1.docker.io/bitnamicharts