apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-example
  namespace: web
  labels:
    app: web-app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-example
  template:
    metadata:
      labels:
        app: web-app-example
    spec:
      containers:
        - name: web-app-example
          image: linsheng24/web-app-example
          ports:
            - containerPort: 3000
