apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-metrics
  namespace: monitoring
  labels:
    app: nodejs-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-metrics
  template:
    metadata:
      labels:
        app: nodejs-metrics
    spec:
      containers:
        - name: nodejs-metrics
          image: stefanprodan/prometheus-nodejs-app:latest
          ports:
            - containerPort: 3000
              name: metrics
