apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-example-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: web.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-example
            port:
              number: 3000