apiVersion: v1
kind: Service
metadata:
  name: web-app-example
  namespace: web
  labels:
    app: web-app-example
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: web-app-example
  type: ClusterIP