apiVersion: v1
kind: Service
metadata:
  name: nodejs-metrics
  namespace: monitoring
  labels:
    app: nodejs-metrics
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: metrics
  selector:
    app: nodejs-metrics
  type: ClusterIP